### ISSUE TITLE
Load From Values?

### ISSUE THREAD

**Issue by aramrw** [dobecad/mal-rs#2]
This crate is really cool, but I'm trying to persist the access and refresh tokens using the config but I can't get it to work with tauri. I've tried moving my .env around, appending stuff myself and even hand coding values into the .env but it can't read it no matter what I do. It might be some kind of tauri safety feature, or just a skill issue (probably).

Is there anyway you can create a function like `load_from_values` that doesn't rely on any .env files and let's me just pass values manually if that's possible, as I would also like to encrypt and store these values in my database myself instead of the .env as well.

**Comment by dobecad** [comment]
Just so I can better understand what you are asking for, does this function not satisfy what you are trying to accomplish:
https://github.com/dobecad/mal-rs/blob/main/mal-api/src/oauth.rs#L307

Ignore the note in that function. It doesn't rely on any environment variables.

**Comment by aramrw** [comment]
My bad I should have tested it before hand.

Thank you for the library, its very good!!
